const reviews = [
	{
		id: 1,
		comment:
			'Great product, highly recommended! Trong đó, chúng ta kiểm tra xem tên sản phẩm có dài hơn 20 ký tự không. Nếu có, chúng ta chỉ lấy 20 ký tự đầu tiên và thêm dấu chấm ở cuối, nếu không thì hiển thị toàn bộ tên sản phẩm.',
		author: 'John Doe',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 2,
		comment: 'I love this store!',
		author: 'Jane Smith',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 3,
		comment: 'Excellent customer service!',
		author: 'Alice Johnson',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 4,
		comment: 'Fantastic quality, exceeded my expectations!',
		author: 'David Brown',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 5,
		comment: 'Fast shipping and great packaging.',
		author: 'Sarah Wilson',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 6,
		comment: "The best online shopping experience I've had.",
		author: 'Michael Lee',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 7,
		comment: 'Incredible selection of products.',
		author: 'Emily Taylor',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 8,
		comment: 'Will definitely be shopping here again!',
		author: 'Robert Martinez',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 9,
		comment: 'Impressed with the variety of options available.',
		author: 'Jennifer Garcia',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 10,
		comment: 'Superb customer support, very helpful.',
		author: 'Daniel Rodriguez',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 11,
		comment: 'Top-notch quality, worth every penny.',
		author: 'Lisa Nguyen',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 12,
		comment: 'Easy checkout process and secure payment.',
		author: 'Matthew Anderson',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 13,
		comment: 'My go-to store for all my shopping needs.',
		author: 'Amanda Thomas',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 14,
		comment: 'Great deals and discounts available.',
		author: 'Christopher Wilson',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 15,
		comment: 'Highly impressed with the product range.',
		author: 'Jessica King',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 16,
		comment: 'Prompt delivery, arrived earlier than expected.',
		author: 'Ryan Taylor',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 17,
		comment: 'Excellent value for money.',
		author: 'Laura Robinson',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 18,
		comment: 'Beautifully packaged, perfect for gifting.',
		author: 'Kevin Wright',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 19,
		comment: 'Very satisfied with my purchase.',
		author: 'Michelle Hall',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 20,
		comment: 'Great communication from the seller.',
		author: 'Kimberly Scott',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 21,
		comment: 'Impressed with the attention to detail.',
		author: 'Steven Green',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 22,
		comment: 'Highly recommended for quality and service.',
		author: 'Melissa Baker',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 23,
		comment: 'The product exceeded my expectations.',
		author: 'Erica Reed',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 24,
		comment: 'User-friendly website and easy navigation.',
		author: 'Gregory Diaz',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 25,
		comment: 'Very happy with my purchase, thank you!',
		author: 'Stephanie Lewis',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 26,
		comment: 'Great selection of products for all occasions.',
		author: 'Charles Ward',
		img: require('../assets/imgs/avatar.png'),
	},
	{
		id: 27,
		comment: 'Excellent shopping experience overall.',
		author: 'Patricia Martinez',
		img: require('../assets/imgs/avatar.png'),
	},
];

export { reviews };
